apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io2  ## This is what determines the storage speed of your SC. Since io2 is Amazon's fastest EBS Volume option, you can use that EBS Volume Type for a "fast" SC option.
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate