apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2  ## This is what determines the storage speed of your SC. Since GP2 is Amazon's slowest EBS Volume option, you can use that EBS Volume Type for a "slow" SC option.
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate